### PR TITLE
chmod mac binary onload

### PR DESCRIPTION
**Pull request by byandrewdavis**
this will make sure the mac binary is chmod to 755, with check to make sure we're on the macos.

### CODE REVIEW

**Comment by bdw429s** [comment]
As an enhancement idea going forward, this can be made to use the `run`  command which will automatically capture any output which might be useful if any errors are encountered.

**Comment by elpete** [comment]
Looks great, @byandrewdavis.  Thanks!

**Comment by elpete** [comment]
@bdw429s I've opened #9 to address your feature request.

**Comment by elpete** [comment]
Published as [1.3.1](https://www.forgebox.io/view/box-ngrok)

**Pull request merged**
